<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class ="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">idProduct</th>
      <th scope="col">Reference</th>
      <th scope="col">Description</th>
      <th scope="col">PriceTaxIncl</th>
      <th scope="col">PriceTaxIncl</th>
    </tr>
  </thead>
    <tbody>
        <?php
        foreach($products as $produit){
            ?>
            <tr>
                <td><?= $produit['idProduct'] ?></td>
                <td><?= $produit['reference'] ?></td>
               
            
            </tr>
            <?php
        }
        ?>
    </tbody>
</table>