<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom Styling -->
    <link rel="stylesheet" href="../css/style.css">

    <!-- Admin Styling -->


    <title> Add Post</title>
</head>

<body>
   
    <div class="admin-container">


        <div class="container">

            <h2 class="page-title"> Gestions des articles</h2>


            <form action="index.php?action=create" method="POST" enctype="multipart/form-data">
                <h2 class="text-center"><strong>Create</strong> a post </h2>
                <label for="description">Description:</label>
    <textarea name="description" id="description" rows="4" cols="50" required></textarea>
    <br>

    <label for="priceTaxIncl">Price (Tax Incl.):</label>
    <input type="number" name="priceTaxIncl" id="priceTaxIncl" step="0.01" required>
    <br>

    <label for="priceTaxExcl">Price (Tax Excl.):</label>
    <input type="number" name="priceTaxExcl" id="priceTaxExcl" step="0.01" required>
    <br>

    <label for="idLang">Language ID:</label>
    <input type="number" name="idLang" id="idLang" required>
    <br>

    <label for="quantity">Quantity:</label>
    <input type="number" name="quantity" id="quantity" required>
    <br>

    <button type="submit">Create Product</button>



              

        </div>

    </div>
    </form>
    <!-- // Admin Content -->

    </div>
    <!-- // Page Wrapper -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>